// This is Proto v3 syntax。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: protobuf/common_game.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 共用的請求進桌
type TS_CommonEnterTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tableid string `protobuf:"bytes,1,opt,name=tableid,proto3" json:"tableid,omitempty"` // 請求進入的桌號
}

func (x *TS_CommonEnterTable) Reset() {
	*x = TS_CommonEnterTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TS_CommonEnterTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TS_CommonEnterTable) ProtoMessage() {}

func (x *TS_CommonEnterTable) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TS_CommonEnterTable.ProtoReflect.Descriptor instead.
func (*TS_CommonEnterTable) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{0}
}

func (x *TS_CommonEnterTable) GetTableid() string {
	if x != nil {
		return x.Tableid
	}
	return ""
}

// 共用的請求進桌回應
type CommonEnterTableRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tableid string `protobuf:"bytes,1,opt,name=tableid,proto3" json:"tableid,omitempty"` // 請求進入的桌號
	Code    uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 錯誤代碼
}

func (x *CommonEnterTableRes) Reset() {
	*x = CommonEnterTableRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonEnterTableRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonEnterTableRes) ProtoMessage() {}

func (x *CommonEnterTableRes) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonEnterTableRes.ProtoReflect.Descriptor instead.
func (*CommonEnterTableRes) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{1}
}

func (x *CommonEnterTableRes) GetTableid() string {
	if x != nil {
		return x.Tableid
	}
	return ""
}

func (x *CommonEnterTableRes) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 共用的請求離桌
type TS_CommonLeaveTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tableid string `protobuf:"bytes,1,opt,name=tableid,proto3" json:"tableid,omitempty"` // 請求的桌號
}

func (x *TS_CommonLeaveTable) Reset() {
	*x = TS_CommonLeaveTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TS_CommonLeaveTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TS_CommonLeaveTable) ProtoMessage() {}

func (x *TS_CommonLeaveTable) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TS_CommonLeaveTable.ProtoReflect.Descriptor instead.
func (*TS_CommonLeaveTable) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{2}
}

func (x *TS_CommonLeaveTable) GetTableid() string {
	if x != nil {
		return x.Tableid
	}
	return ""
}

// 共用的請求離桌回應
type CommonLeaveTableRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tableid string `protobuf:"bytes,1,opt,name=tableid,proto3" json:"tableid,omitempty"` // 請求的桌號
	Code    uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 錯誤代碼
}

func (x *CommonLeaveTableRes) Reset() {
	*x = CommonLeaveTableRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonLeaveTableRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonLeaveTableRes) ProtoMessage() {}

func (x *CommonLeaveTableRes) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonLeaveTableRes.ProtoReflect.Descriptor instead.
func (*CommonLeaveTableRes) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{3}
}

func (x *CommonLeaveTableRes) GetTableid() string {
	if x != nil {
		return x.Tableid
	}
	return ""
}

func (x *CommonLeaveTableRes) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type KickPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason uint32 `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"` //踢人的理由 0閒置局數過多 1閒置秒數過久 2被操盤ban掉 3:CBGO沒有下一局，回合結束時踢人 4: 維護中 5: Pid 禁用中
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`      //玩家pid+username
}

func (x *KickPlayer) Reset() {
	*x = KickPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayer) ProtoMessage() {}

func (x *KickPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayer.ProtoReflect.Descriptor instead.
func (*KickPlayer) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{4}
}

func (x *KickPlayer) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *KickPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type IdleKickNotice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason      uint32 `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"`           //踢人的理由 0閒置局數過多 1閒置秒數過久 2被操盤ban掉
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                //玩家pid+username
	Idleround   uint32 `protobuf:"varint,3,opt,name=idleround,proto3" json:"idleround,omitempty"`     //已經閒置幾局
	Remainround uint32 `protobuf:"varint,4,opt,name=remainround,proto3" json:"remainround,omitempty"` //剩下閒置幾局會被踢掉
}

func (x *IdleKickNotice) Reset() {
	*x = IdleKickNotice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdleKickNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdleKickNotice) ProtoMessage() {}

func (x *IdleKickNotice) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdleKickNotice.ProtoReflect.Descriptor instead.
func (*IdleKickNotice) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{5}
}

func (x *IdleKickNotice) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *IdleKickNotice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdleKickNotice) GetIdleround() uint32 {
	if x != nil {
		return x.Idleround
	}
	return 0
}

func (x *IdleKickNotice) GetRemainround() uint32 {
	if x != nil {
		return x.Remainround
	}
	return 0
}

type KickTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason uint32 `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"` //踢人的理由 0閒置局數過多 1閒置秒數過久 2被操盤ban掉
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`      //玩家pid+username
}

func (x *KickTable) Reset() {
	*x = KickTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickTable) ProtoMessage() {}

func (x *KickTable) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickTable.ProtoReflect.Descriptor instead.
func (*KickTable) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{6}
}

func (x *KickTable) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *KickTable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 聊天用玩家ID
type ChatID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chatid uint32 `protobuf:"varint,1,opt,name=chatid,proto3" json:"chatid,omitempty"` // 聊天用玩家ID
}

func (x *ChatID) Reset() {
	*x = ChatID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatID) ProtoMessage() {}

func (x *ChatID) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatID.ProtoReflect.Descriptor instead.
func (*ChatID) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{7}
}

func (x *ChatID) GetChatid() uint32 {
	if x != nil {
		return x.Chatid
	}
	return 0
}

// 聊天訊息
type TS_SentChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` //聊天訊息
}

func (x *TS_SentChatMessage) Reset() {
	*x = TS_SentChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TS_SentChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TS_SentChatMessage) ProtoMessage() {}

func (x *TS_SentChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TS_SentChatMessage.ProtoReflect.Descriptor instead.
func (*TS_SentChatMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{8}
}

func (x *TS_SentChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 聊天訊息回包
type SentChatMessageR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 結果
}

func (x *SentChatMessageR) Reset() {
	*x = SentChatMessageR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentChatMessageR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentChatMessageR) ProtoMessage() {}

func (x *SentChatMessageR) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentChatMessageR.ProtoReflect.Descriptor instead.
func (*SentChatMessageR) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{9}
}

func (x *SentChatMessageR) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 廣播聊天訊息
type ChatMessageBoardcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chatid   uint32 `protobuf:"varint,1,opt,name=chatid,proto3" json:"chatid,omitempty"`    // 聊天用玩家ID
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`   // 訊息
	MaskName string `protobuf:"bytes,3,opt,name=maskName,proto3" json:"maskName,omitempty"` // 玩家名稱
}

func (x *ChatMessageBoardcast) Reset() {
	*x = ChatMessageBoardcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessageBoardcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageBoardcast) ProtoMessage() {}

func (x *ChatMessageBoardcast) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageBoardcast.ProtoReflect.Descriptor instead.
func (*ChatMessageBoardcast) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{10}
}

func (x *ChatMessageBoardcast) GetChatid() uint32 {
	if x != nil {
		return x.Chatid
	}
	return 0
}

func (x *ChatMessageBoardcast) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatMessageBoardcast) GetMaskName() string {
	if x != nil {
		return x.MaskName
	}
	return ""
}

// 桌台資訊
// 包含 *桌號* *狀態Flag*
type TableData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tableid string `protobuf:"bytes,1,opt,name=tableid,proto3" json:"tableid,omitempty"` // 桌號
	Flag    uint32 `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`      // 狀態Flag
}

func (x *TableData) Reset() {
	*x = TableData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableData) ProtoMessage() {}

func (x *TableData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableData.ProtoReflect.Descriptor instead.
func (*TableData) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{11}
}

func (x *TableData) GetTableid() string {
	if x != nil {
		return x.Tableid
	}
	return ""
}

func (x *TableData) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

//桌台清單廣播
type TableList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*TableData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *TableList) Reset() {
	*x = TableList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableList) ProtoMessage() {}

func (x *TableList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableList.ProtoReflect.Descriptor instead.
func (*TableList) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{12}
}

func (x *TableList) GetData() []*TableData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GameCurrencyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                  // 貨幣名稱
	Limitmin     string `protobuf:"bytes,2,opt,name=limitmin,proto3" json:"limitmin,omitempty"`          // 最小投注單位
	Limitmax     string `protobuf:"bytes,3,opt,name=limitmax,proto3" json:"limitmax,omitempty"`          // 最大投注單位
	Profitlimit  string `protobuf:"bytes,4,opt,name=profitlimit,proto3" json:"profitlimit,omitempty"`    // 獲利上限
	CurrencyType uint32 `protobuf:"varint,5,opt,name=currencyType,proto3" json:"currencyType,omitempty"` // 類型 0:虛擬 1:法幣
}

func (x *GameCurrencyData) Reset() {
	*x = GameCurrencyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameCurrencyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCurrencyData) ProtoMessage() {}

func (x *GameCurrencyData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCurrencyData.ProtoReflect.Descriptor instead.
func (*GameCurrencyData) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{13}
}

func (x *GameCurrencyData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameCurrencyData) GetLimitmin() string {
	if x != nil {
		return x.Limitmin
	}
	return ""
}

func (x *GameCurrencyData) GetLimitmax() string {
	if x != nil {
		return x.Limitmax
	}
	return ""
}

func (x *GameCurrencyData) GetProfitlimit() string {
	if x != nil {
		return x.Profitlimit
	}
	return ""
}

func (x *GameCurrencyData) GetCurrencyType() uint32 {
	if x != nil {
		return x.CurrencyType
	}
	return 0
}

type TableCurrencyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tableid      string              `protobuf:"bytes,1,opt,name=tableid,proto3" json:"tableid,omitempty"`           // 桌號
	MaxRate      uint32              `protobuf:"varint,2,opt,name=maxRate,proto3" json:"maxRate,omitempty"`          // 最大開獎倍率
	MinRate      uint32              `protobuf:"varint,3,opt,name=minRate,proto3" json:"minRate,omitempty"`          // 最小開獎倍率
	Currencydata []*GameCurrencyData `protobuf:"bytes,4,rep,name=currencydata,proto3" json:"currencydata,omitempty"` // 貨幣資料
}

func (x *TableCurrencyInfo) Reset() {
	*x = TableCurrencyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableCurrencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCurrencyInfo) ProtoMessage() {}

func (x *TableCurrencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCurrencyInfo.ProtoReflect.Descriptor instead.
func (*TableCurrencyInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{14}
}

func (x *TableCurrencyInfo) GetTableid() string {
	if x != nil {
		return x.Tableid
	}
	return ""
}

func (x *TableCurrencyInfo) GetMaxRate() uint32 {
	if x != nil {
		return x.MaxRate
	}
	return 0
}

func (x *TableCurrencyInfo) GetMinRate() uint32 {
	if x != nil {
		return x.MinRate
	}
	return 0
}

func (x *TableCurrencyInfo) GetCurrencydata() []*GameCurrencyData {
	if x != nil {
		return x.Currencydata
	}
	return nil
}

type PlayerCanUseCurrencyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerCanUseCurrency []string `protobuf:"bytes,1,rep,name=playerCanUseCurrency,proto3" json:"playerCanUseCurrency,omitempty"` // 玩家可以使用的貨幣資料
}

func (x *PlayerCanUseCurrencyData) Reset() {
	*x = PlayerCanUseCurrencyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerCanUseCurrencyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCanUseCurrencyData) ProtoMessage() {}

func (x *PlayerCanUseCurrencyData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCanUseCurrencyData.ProtoReflect.Descriptor instead.
func (*PlayerCanUseCurrencyData) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerCanUseCurrencyData) GetPlayerCanUseCurrency() []string {
	if x != nil {
		return x.PlayerCanUseCurrency
	}
	return nil
}

type ExchangeRateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source   string                       `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`     //來源貨幣
	DestData []*ExchangeRateData_DestData `protobuf:"bytes,2,rep,name=destData,proto3" json:"destData,omitempty"` //清單
}

func (x *ExchangeRateData) Reset() {
	*x = ExchangeRateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeRateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateData) ProtoMessage() {}

func (x *ExchangeRateData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateData.ProtoReflect.Descriptor instead.
func (*ExchangeRateData) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{16}
}

func (x *ExchangeRateData) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExchangeRateData) GetDestData() []*ExchangeRateData_DestData {
	if x != nil {
		return x.DestData
	}
	return nil
}

type ProductExchangeRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid  string              `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`   //產品編號
	Data []*ExchangeRateData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"` //匯率資料
}

func (x *ProductExchangeRate) Reset() {
	*x = ProductExchangeRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductExchangeRate) ProtoMessage() {}

func (x *ProductExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductExchangeRate.ProtoReflect.Descriptor instead.
func (*ProductExchangeRate) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{17}
}

func (x *ProductExchangeRate) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *ProductExchangeRate) GetData() []*ExchangeRateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClientUsingCurrency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username       string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`             // 玩家名稱
	CryptoCurrency string `protobuf:"bytes,2,opt,name=cryptoCurrency,proto3" json:"cryptoCurrency,omitempty"` // 使用虛擬貨幣
	FiatCurrency   string `protobuf:"bytes,3,opt,name=fiatCurrency,proto3" json:"fiatCurrency,omitempty"`     // 使用法幣 沒使用會是空字串
}

func (x *ClientUsingCurrency) Reset() {
	*x = ClientUsingCurrency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientUsingCurrency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUsingCurrency) ProtoMessage() {}

func (x *ClientUsingCurrency) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUsingCurrency.ProtoReflect.Descriptor instead.
func (*ClientUsingCurrency) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{18}
}

func (x *ClientUsingCurrency) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientUsingCurrency) GetCryptoCurrency() string {
	if x != nil {
		return x.CryptoCurrency
	}
	return ""
}

func (x *ClientUsingCurrency) GetFiatCurrency() string {
	if x != nil {
		return x.FiatCurrency
	}
	return ""
}

// 更新貨幣資訊
type CurrencyDataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency []*CurrencyDataList_CurrencyData `protobuf:"bytes,1,rep,name=currency,proto3" json:"currency,omitempty"` // 用戶身上的貨幣類別
	//auxiliary.GameRoundInfo roundinfo = 2;	// gameround 資訊
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 時間戳記
}

func (x *CurrencyDataList) Reset() {
	*x = CurrencyDataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyDataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyDataList) ProtoMessage() {}

func (x *CurrencyDataList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyDataList.ProtoReflect.Descriptor instead.
func (*CurrencyDataList) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{19}
}

func (x *CurrencyDataList) GetCurrency() []*CurrencyDataList_CurrencyData {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *CurrencyDataList) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 請求刷新貨幣資訊
type TS_RefreshCurrencyDataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TS_RefreshCurrencyDataList) Reset() {
	*x = TS_RefreshCurrencyDataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TS_RefreshCurrencyDataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TS_RefreshCurrencyDataList) ProtoMessage() {}

func (x *TS_RefreshCurrencyDataList) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TS_RefreshCurrencyDataList.ProtoReflect.Descriptor instead.
func (*TS_RefreshCurrencyDataList) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{20}
}

type ExchangeRateData_DestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest string `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"` //目標貨幣
	Rate string `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"` //匯率
}

func (x *ExchangeRateData_DestData) Reset() {
	*x = ExchangeRateData_DestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeRateData_DestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateData_DestData) ProtoMessage() {}

func (x *ExchangeRateData_DestData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateData_DestData.ProtoReflect.Descriptor instead.
func (*ExchangeRateData_DestData) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{16, 0}
}

func (x *ExchangeRateData_DestData) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *ExchangeRateData_DestData) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

type CurrencyDataList_CurrencyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrencyType string `protobuf:"bytes,1,opt,name=currencyType,proto3" json:"currencyType,omitempty"` //貨幣種類
	Amount       string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`             //貨幣數量
}

func (x *CurrencyDataList_CurrencyData) Reset() {
	*x = CurrencyDataList_CurrencyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_common_game_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyDataList_CurrencyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyDataList_CurrencyData) ProtoMessage() {}

func (x *CurrencyDataList_CurrencyData) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_common_game_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyDataList_CurrencyData.ProtoReflect.Descriptor instead.
func (*CurrencyDataList_CurrencyData) Descriptor() ([]byte, []int) {
	return file_protobuf_common_game_proto_rawDescGZIP(), []int{19, 0}
}

func (x *CurrencyDataList_CurrencyData) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *CurrencyDataList_CurrencyData) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_protobuf_common_game_proto protoreflect.FileDescriptor

var file_protobuf_common_game_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x2f, 0x0a, 0x13, 0x54, 0x53, 0x5f, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2f, 0x0a, 0x13,
	0x54, 0x53, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x22, 0x43, 0x0a,
	0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x38, 0x0a, 0x0a, 0x4b, 0x69, 0x63, 0x6b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a, 0x0e,
	0x49, 0x64, 0x6c, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64,
	0x6c, 0x65, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69,
	0x64, 0x6c, 0x65, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x37, 0x0a, 0x09, 0x4b, 0x69,
	0x63, 0x6b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x68, 0x61, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x12, 0x54, 0x53, 0x5f, 0x53, 0x65, 0x6e, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x64, 0x0a,
	0x14, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x73, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x73, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x34,
	0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x6d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x6d, 0x61, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x74, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x11,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x61, 0x78, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x61,
	0x78, 0x52, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x52, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x12,
	0x3e, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x4e, 0x0a, 0x18, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x14, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x43, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22,
	0x9f, 0x01, 0x0a, 0x10, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x08,
	0x64, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x32, 0x0a,
	0x08, 0x44, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61, 0x74,
	0x65, 0x22, 0x57, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x45, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7d, 0x0a, 0x13, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x69, 0x6e, 0x67, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x69, 0x61, 0x74, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x61,
	0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0xc1, 0x01, 0x0a, 0x10, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x43,
	0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x1a, 0x4a, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1c, 0x0a,
	0x1a, 0x54, 0x53, 0x5f, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x73, 0x79, 0x61, 0x6f,
	0x72, 0x61, 0x6e, 0x35, 0x31, 0x2f, 0x47, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_common_game_proto_rawDescOnce sync.Once
	file_protobuf_common_game_proto_rawDescData = file_protobuf_common_game_proto_rawDesc
)

func file_protobuf_common_game_proto_rawDescGZIP() []byte {
	file_protobuf_common_game_proto_rawDescOnce.Do(func() {
		file_protobuf_common_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_common_game_proto_rawDescData)
	})
	return file_protobuf_common_game_proto_rawDescData
}

var file_protobuf_common_game_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_protobuf_common_game_proto_goTypes = []interface{}{
	(*TS_CommonEnterTable)(nil),           // 0: protobuf.TS_CommonEnterTable
	(*CommonEnterTableRes)(nil),           // 1: protobuf.CommonEnterTableRes
	(*TS_CommonLeaveTable)(nil),           // 2: protobuf.TS_CommonLeaveTable
	(*CommonLeaveTableRes)(nil),           // 3: protobuf.CommonLeaveTableRes
	(*KickPlayer)(nil),                    // 4: protobuf.KickPlayer
	(*IdleKickNotice)(nil),                // 5: protobuf.IdleKickNotice
	(*KickTable)(nil),                     // 6: protobuf.KickTable
	(*ChatID)(nil),                        // 7: protobuf.ChatID
	(*TS_SentChatMessage)(nil),            // 8: protobuf.TS_SentChatMessage
	(*SentChatMessageR)(nil),              // 9: protobuf.SentChatMessageR
	(*ChatMessageBoardcast)(nil),          // 10: protobuf.ChatMessageBoardcast
	(*TableData)(nil),                     // 11: protobuf.TableData
	(*TableList)(nil),                     // 12: protobuf.TableList
	(*GameCurrencyData)(nil),              // 13: protobuf.GameCurrencyData
	(*TableCurrencyInfo)(nil),             // 14: protobuf.TableCurrencyInfo
	(*PlayerCanUseCurrencyData)(nil),      // 15: protobuf.PlayerCanUseCurrencyData
	(*ExchangeRateData)(nil),              // 16: protobuf.ExchangeRateData
	(*ProductExchangeRate)(nil),           // 17: protobuf.ProductExchangeRate
	(*ClientUsingCurrency)(nil),           // 18: protobuf.ClientUsingCurrency
	(*CurrencyDataList)(nil),              // 19: protobuf.CurrencyDataList
	(*TS_RefreshCurrencyDataList)(nil),    // 20: protobuf.TS_RefreshCurrencyDataList
	(*ExchangeRateData_DestData)(nil),     // 21: protobuf.ExchangeRateData.DestData
	(*CurrencyDataList_CurrencyData)(nil), // 22: protobuf.CurrencyDataList.CurrencyData
}
var file_protobuf_common_game_proto_depIdxs = []int32{
	11, // 0: protobuf.TableList.data:type_name -> protobuf.TableData
	13, // 1: protobuf.TableCurrencyInfo.currencydata:type_name -> protobuf.GameCurrencyData
	21, // 2: protobuf.ExchangeRateData.destData:type_name -> protobuf.ExchangeRateData.DestData
	16, // 3: protobuf.ProductExchangeRate.data:type_name -> protobuf.ExchangeRateData
	22, // 4: protobuf.CurrencyDataList.currency:type_name -> protobuf.CurrencyDataList.CurrencyData
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_common_game_proto_init() }
func file_protobuf_common_game_proto_init() {
	if File_protobuf_common_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_common_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TS_CommonEnterTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonEnterTableRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TS_CommonLeaveTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonLeaveTableRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdleKickNotice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TS_SentChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SentChatMessageR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessageBoardcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameCurrencyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableCurrencyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerCanUseCurrencyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeRateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductExchangeRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientUsingCurrency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyDataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TS_RefreshCurrencyDataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeRateData_DestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_common_game_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyDataList_CurrencyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_common_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_common_game_proto_goTypes,
		DependencyIndexes: file_protobuf_common_game_proto_depIdxs,
		MessageInfos:      file_protobuf_common_game_proto_msgTypes,
	}.Build()
	File_protobuf_common_game_proto = out.File
	file_protobuf_common_game_proto_rawDesc = nil
	file_protobuf_common_game_proto_goTypes = nil
	file_protobuf_common_game_proto_depIdxs = nil
}
